CREATE DATABASE IF NOT EXISTS ${DB_NAME};
CREATE USER IF NOT EXISTS '${WP_DB_USER}'@'%' IDENTIFIED by '${WP_DB_PASSWORD}';
GRANT ALL PRIVILEGES ON ${DB_NAME}.* TO '${WP_DB_USER}'@'%' WITH GRANT OPTION;
GRANT ALL ON *.* TO 'root'@'localhost' identified by '$WP_DB_PASSWORD' WITH GRANT OPTION ;
SET PASSWORD FOR 'root'@'localhost'=PASSWORD('${DB_PASSWORD}');
FLUSH PRIVILEGES;
